# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# gazebo_ros_control:
#   pid_gains:
#     wheel_left_joint: {p: 100.0, i: 0.0, d: 0.0}
#     wheel_right_joint: {p: 100.0, i: 0.0, d: 0.0}

# Joint Controllers ---------------------------------------
# leftWheel_effort_controller:
#   type: effort_controllers/JointEffortController
#   joint: wheel_left_joint
#   pid: {p: 100.0, i: 0.1, d: 10.0}
# rightWheel_effort_controller:
#   type: effort_controllers/JointEffortController
#   joint: wheel_right_joint
#   pid: {p: 100.0, i: 0.1, d: 10.0}

mobile_base_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: wheel_left_joint
  right_wheel: wheel_right_joint
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  cmd_vel_timeout: 0.25
  wheel_radius: ${wheel_radius}
  linear/x/has_max_velocity: true
  linear/x/max_velocity: 2.0
  linear/x/has_acceleration_limits: true
  linear/x/max_acceleration: 5.0
  linear/x/min_acceleration: -4.0
hip_position_controller:
  type: effort_controllers/JointPositionController
  joint: lower_body_hip_joint
  pid: {p: 100.0, i: 0.1, d: 10.0}
upperBody_position_controller:
  type: effort_controllers/JointPositionController
  joint: hip_upper_body_joint
  pid: {p: 100.0, i: 0.1, d: 10.0}
leftShoulder_position_controller:
  type: effort_controllers/JointPositionController
  joint: upper_body_shoulder_left_joint
  pid: {p: 100.0, i: 0.1, d: 10.0}
rightShoulder_position_controller:
  type: effort_controllers/JointPositionController
  joint: upper_body_shoulder_right_joint
  pid: {p: 100.0, i: 0.1, d: 10.0}
leftArm_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_arm_left_joint
  pid: {p: 100.0, i: 0.1, d: 10.0}
rightArm_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_arm_right_joint
  pid: {p: 100.0, i: 0.1, d: 10.0}
neck_position_controller:
  type: effort_controllers/JointPositionController
  joint: upper_body_neck_joint
  pid: {p: 100.0, i: 0.1, d: 10.0}
head_position_controller:
  type: effort_controllers/JointPositionController
  joint: neck_head_joint
  pid: {p: 100.0, i: 0.1, d: 10.0}
